"""Add open_to_internal_opportunities to candidate_profiles

Revision ID: 3f6b897c24db
Revises: 9fd44cd9db50
Create Date: 2026-08-09 23:30:56.358271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6b897c24db'
down_revision: Union[str, None] = '9fd44cd9db50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('open_to_internal_opportunities', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'open_to_internal_opportunities')
    # ### end Alembic commands ###
