"""Add application_status and applied_at to matches

Revision ID: 3ff6702cbbbb
Revises: 3f6b897c24db
Create Date: 2026-08-10 10:18:24.393414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff6702cbbbb'
down_revision: Union[str, None] = '3f6b897c24db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('application_status', sa.Enum('not_applied', 'applied', 'withdrawn', name='applicationstatus'), nullable=False, server_default='not_applied'))
    op.add_column('matches', sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'applied_at')
    op.drop_column('matches', 'application_status')
    # ### end Alembic commands ###
