"""Add employee_type to candidate_profiles

Revision ID: 9fd44cd9db50
Revises: f969731b5aad
Create Date: 2026-08-05 13:26:49.160461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd44cd9db50'
down_revision: Union[str, None] = 'f969731b5aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('employee_type', sa.Enum('internal', 'external', name='employeetype'), nullable=False, server_default='external'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'employee_type')
    # ### end Alembic commands ###
